### ISSUE TITLE
Build failure with hspec-junit-formatter-1.1.0.0

### ISSUE THREAD

**Issue by snoyberg** [freckle/freckle-app#43]
```
[13 of 20] Compiling Freckle.App.Test.Hspec.Runner

/var/stackage/work/unpack-dir/unpacked/freckle-app-1.0.0.4-4a8b4f8964784f4048fbd2ad53adaccc053f006c44eb3673024fbe487228aaff/library/Freckle/App/Test/Hspec/Runner.hs:18:1: error:
    Could not find module ‘Test.HSpec.JUnit’
    Perhaps you meant
      Test.Hspec.JUnit (from hspec-junit-formatter-1.1.0.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import Test.HSpec.JUnit (runJUnitSpec)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pbrisbin** [comment]
:wave: we had a few hiccups with the `HSpec`/`Hspec` change that caused some quick version churn between these two packages. This is fixed in `freckle-app-1.0.2.2`, which works with `hspec-junit-formatter` newer than `1.0.3.0`.

**Comment by snoyberg** [comment]
Thanks!

**Comment by snoyberg** [comment]
Just noticed that due to https://github.com/commercialhaskell/stackage/issues/6273, this doesn't resolve the issue for Stackage.

**Comment by pbrisbin** [comment]
Sorry, I sometimes have trouble understanding the relation between various Stackage issues. What is the reason that issue being open means this one must also be open?

**Comment by snoyberg** [comment]
Since ekg isn't is Stackage, we can't include the newer version of freckle-app, which depends on it. And the older version is incompatible with hspec-junit-formatter-1.1.0.0

**Comment by pbrisbin** [comment]
I see. But this only blocks us being in `lts-19.x` right? `lts-18` won't be allowed off `hspec-junit-formatter-1.0.x` so everything will stay in that line?

**Comment by snoyberg** [comment]
Yes, that's true.

**Comment by pbrisbin** [comment]
My understanding of the current state of things:

- The build failure in this Issue was addressed
- freckle-app (and hspec-junit-formatter < 1.1) are in lts-18.x
- freckle-app cannot be in lts-19.x because ekg has dropped out
- ekg just needs a new release, but maintainers have gone silent see [here](https://github.com/commercialhaskell/stackage/issues/6273#issuecomment-1031773576)
- freckle-app is now (also?) disabled because of aeson-2.0

Therefore, I think this Issue need not be open. If anything, we should have an Issue about aeson-2.0.
